[ALPS07713407] common: fix thermal_zone_of_device_ops build breaks
Follow commit f59ac19b7f44 ("thermal/of: Remove old OF code") to
move to new OF APIs and fix the following build breaks:

connectivity/common/common_main/platform/mtk_wcn_consys_hw.c:179:48:
error: variable has incomplete type
const struct thermal_zone_of_device_ops
connectivity/common/common_main/platform/mtk_wcn_consys_hw.c:342:7:
error: call to undeclared function
devm_thermal_zone_of_sensor_register; ISO C99 and later do not
support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 0acddfa9b8963bd3de98ef13d8a7f8d5e28af9d4

Signed-off-by: Miles Chen <miles.chen@mediatek.com>
CR-Id: ALPS07713407
Feature: Kernel SI Operation
Change-Id: I10a88ec4cf0903993a9f6f58171922acfdf006f5